log-level: info

allow-lan: true

ipv6: true

external-controller: 0.0.0.0:9090
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true

find-process-mode: off

global-client-fingerprint: chrome

unified-delay: true

# ==================global config end=====================

# 按照目前的规则，启动的时候和解析订阅的时候dns发送给smartdns
# smartdns根据规则进行解析，如果链接是国内的，那么是没问题的，
# 但是如果链接是国外的, smartdns会利用海外发送，此时如果dae那边没有可用节点
# 解析就会失败. 如果出现这种情况，就启用如下配置利用国内dns发出去解析.
# 一般不太可能出现, 我们默认节点都是可以从国内dns获取的
dns:
  enable: true
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - 119.29.29.29

# 实际上部分流量根本不会经过mihomo，所以这里要不要skip部分ip之类的无所谓
# dae已经会进行sniff了, 其实mihomo没有必要再次sniff, 如果需要sniff再考虑
sniffer:
  enable: false
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

proxy-providers:
  niubi:
    type: http
    url: "subscription link"
    interval: 1800
    proxy: DIRECT
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      additional-prefix: "[niubi]"
      skip-cert-verify: false
  linghunyun:
    type: http
    url: "subscription link"
    interval: 1800
    proxy: DIRECT
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      additional-prefix: "[linghunyun]"
      skip-cert-verify: false

proxy-groups:
  - name: "Near"
    type: url-test
    use:
      - niubi
      - linghunyun
    url: https://cp.cloudflare.com
    interval: 300
    exclude-filter: "套餐|到期|线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)港|台|新|日|韩|hk|tw|sg|jp|kr"

  - name: "AI"
    type: url-test
    use:
      - niubi
      - linghunyun
    url: https://cp.cloudflare.com
    interval: 300
    exclude-filter: "套餐|到期|线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)gpt|新|日|美|加|澳|德|us|ca|au|jp"

  - name: "West"
    type: url-test
    use:
      - niubi
      - linghunyun
    url: https://cp.cloudflare.com
    interval: 300
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)gpt|新|日|美|加|澳|德|us|ca|au|jp"

  - name: "Auto"
    type: url-test
    use:
      - niubi
      - linghunyun
    url: https://cp.cloudflare.com
    interval: 300
    exclude-filter: "套餐|到期|线路|订阅|更新|流量|剩余|0.1x"

  - name: "Select"
    type: select
    use:
      - niubi
      - linghunyun
    url: https://cp.cloudflare.com
    interval: 300
    exclude-filter: "套餐|到期|线路|订阅|更新|流量|剩余|0.1x"

listeners:
  - name: socks5-Auto
    type: socks
    port: 10800
    #listen: 0.0.0.0 # 默认监听 0.0.0.0
    # rule: sub-rule-name1 # 默认使用 rules,如果未找到 sub-rule 则直接使用 rules
    # proxy: HK_proxy # 如果不为空则直接将该入站流量交由指定proxy处理
    # udp: false # 默认 true
  - name: socks5-Near
    type: socks
    port: 10801
  - name: socks5-AI
    type: socks
    port: 10802
  - name: socks5-West
    type: socks
    port: 10803
  - name: socks5-Select
    type: socks
    port: 10804

rules:
  - IN-NAME,socks5-Near,Near
  - IN-NAME,socks5-AI,AI
  - IN-NAME,socks5-West,West
  - IN-NAME,socks5-Select,Select
  - IN-NAME,socks5-Auto,Auto
  - MATCH,Auto
