log-level: info

allow-lan: true

ipv6: true

external-controller: 0.0.0.0:9090
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true
secret: enter_secret

find-process-mode: off

global-client-fingerprint: chrome

unified-delay: true

# ==================global config end=====================

# 按照目前的规则，启动的时候和解析订阅的时候dns发送给smartdns
# smartdns根据规则进行解析，如果链接是国内的，那么是没问题的，
# 但是如果链接是国外的, smartdns会利用海外发送，此时如果dae那边没有可用节点
# 解析就会失败. 如果出现这种情况，就启用如下配置利用国内dns发出去解析.
# 一般不太可能出现, 我们默认节点都是可以从国内dns获取的

proxy-providers:
  NiuBi:
    type: http
    url: "subscription link"
    interval: 1800
    proxy: DIRECT
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      additional-prefix: "[NiuBi]"
      skip-cert-verify: false

proxy-groups:
  - name: "HK_proxy"
    type: url-test
    url: https://cp.cloudflare.com
    interval: 300
    include-all: true
    exclude-type: direct
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: "Near_proxy"
    type: url-test
    url: https://cp.cloudflare.com
    interval: 300
    include-all: true
    exclude-type: direct
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)台|tw|taiwan|新|SG|日|JP|韩|KR"

  - name: "Western_proxy"
    type: url-test
    url: https://cp.cloudflare.com
    interval: 300
    include-all: true
    exclude-type: direct
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"
    filter: "(?i)台|tw|taiwan|新|SG|日|JP|韩|KR|US|美|CA|加|澳|AU"

  - name: "Auto"
    type: url-test
    url: https://cp.cloudflare.com
    interval: 300
    include-all: true
    exclude-type: direct
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"

  - name: "Select"
    type: select
    url: https://cp.cloudflare.com
    interval: 300
    include-all: true
    exclude-type: direct
    exclude-filter: "线路|订阅|更新|流量|剩余|0.1x"

listeners:
  - name: socks5-Auto
    type: socks
    port: 10800
    #listen: 0.0.0.0 # 默认监听 0.0.0.0
    # rule: sub-rule-name1 # 默认使用 rules,如果未找到 sub-rule 则直接使用 rules
    # proxy: HK_proxy # 如果不为空则直接将该入站流量交由指定proxy处理
    # udp: false # 默认 true
  - name: socks5-Near
    type: socks
    port: 10801
  - name: socks5-AI
    type: socks
    port: 10802
  - name: socks5-West
    type: socks
    port: 10803
  - name: socks5-Select
    type: socks
    port: 10804

rules:
  - IN-NAME,socks5-Auto,Auto
  - IN-NAME,socks5-Near,Near_proxy
  - IN-NAME,socks5-AI,Western_proxy
  - IN-NAME,socks5-West,Western_proxy
  - MATCH,Auto
